source = ~/.config/omarchy/current/theme/hyprlock.conf
 
general {
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background-lock
    blur_passes = 3
    blur_size = 7
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 650, 100
    position = 0, -150
    halign = center
    valign = center

    inner_color = rgba(255, 255, 255, 0.1)
    outer_color = $source_color
    outline_thickness = 3

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text = as the Nights Reincarnation...
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fade_on_empty = true

    rounding = 22
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

# image {
#     monitor =
#     path = /home/lia/.config/hypr/sakuramoyu.png
#     size = 500
#     rounding = 0
#     border_size = 0
#
#     position = 0, -30
#     halign = center
#     valign = center
#
#     # shadow_passes = 1 # 如果想要阴影效果可以保留
# }

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = rgba(255, 255, 255, 1.0)
    font_size = 160
    font_family = JetBrainsMono Nerd Font Propo
    shadow_passes = 1
    shadow_size = 0
    shadow_color = rgba(94, 94, 94, 0.5)

    position = 0, 420
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = rgba(255, 255, 255, 1.0)
    font_size = 160
    font_family = JetBrainsMono Nerd Font Propo
    shadow_passes = 1
    shadow_size = 0
    shadow_color = rgba(94, 94, 94, 0.5)

    position = 0, 220
    halign = center
    valign = center
}


# label {
#     monitor = 
#     text = $TIME 
#     font_size = 230
#     font_family = CaskaydiaMono Nerd Font
#     color = rgba(255, 255, 255, 1.0)
#     shadow_passes = 2
#     shadow_color = rgba(94, 94, 94, 0.5)
#
#     # 垂直居中，靠上一些
#     position = 0, 400
#     halign = center
#     valign = center
# }

label {
    monitor = 
    text = cmd[update:10000] ~/.config/hypr/get_hitokoto.sh
    font_size = 20
    font_family = CaskaydiaMono Nerd Font
    color = rgba(200, 200, 200, 0.9)
    text_align = center
    position = 0, -500
}
