source = ~/.config/omarchy/current/theme/hyprlock.conf

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
    blur_size = 7
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 650, 100
    position = 0, -200
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text = as the Nights Reincarnation...
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}

image {
    monitor =
    path = /home/lia/.config/hypr/sakuramoyu.png
    size = 300
    rounding = -1
    border_size = 0
    
    position = 0, 20
    halign = center
    valign = center
    
    # shadow_passes = 1 # 如果想要阴影效果可以保留
}

label {
    monitor = 
    text = $TIME 
    font_size = 230
    font_family = CaskaydiaMono Nerd Font
    color = rgba(255, 255, 255, 1.0)
    shadow_passes = 2
    shadow_color = rgba(94, 94, 94, 0.5)
    
    # 垂直居中，靠上一些
    position = 0, 400
    halign = center
    valign = center
}

label {
    monitor = 
    text = cmd[update:10000] ~/.config/hypr/get_hitokoto.sh
    font_size = 20
    font_family = CaskaydiaMono Nerd Font
    color = rgba(200, 200, 200, 0.9)
    text_align = center
    position = 0, -500
}
