#!/bin/bash

# 配置路径
BG_DIR="$HOME/.config/omarchy/current/theme/backgrounds/"
LINK="$HOME/.config/omarchy/current/background"

SCRIPT_DIR="$HOME/.config/rofi"

SELECTED=$(find "$BG_DIR" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.webp" \) | sort | while read -r filepath; do
    filename=$(basename "$filepath")
    echo -en "${filename}\0icon\x1f${filepath}\n"
done | rofi -dmenu -i -p " " -theme "$SCRIPT_DIR/wallpaper-theme.rasi") 

if [[ -n "$SELECTED" ]]; then
    ln -nsf "$BG_DIR/$SELECTED" "$LINK"
    pkill -x swaybg
    setsid uwsm-app -- awww img --transition-type grow --transition-pos 0.8,0.9 "$LINK" >/dev/null 2>&1
    notify-send "Wallpaper Set" "$SELECTED"
fi
